-- COGOTEO RGC - Supabase schema
-- Ejecuta todo este archivo en Supabase > SQL Editor.

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  is_admin boolean not null default false,
  created_at timestamptz not null default now()
);

create table if not exists public.teams (
  id bigint generated by default as identity primary key,
  name text not null,
  players text[] not null default '{}',
  description text not null default '',
  created_at timestamptz not null default now()
);

create table if not exists public.posts (
  id bigint generated by default as identity primary key,
  team_id bigint not null references public.teams(id) on delete cascade,
  played_at timestamptz not null,
  players text[] not null default '{}',
  description text not null default '',
  created_at timestamptz not null default now()
);

create table if not exists public.media (
  id bigint generated by default as identity primary key,
  post_id bigint not null references public.posts(id) on delete cascade,
  storage_path text not null,
  public_url text not null,
  media_type text not null check (media_type in ('image','video')),
  sort_order integer not null default 0,
  created_at timestamptz not null default now()
);

alter table public.profiles enable row level security;
alter table public.teams enable row level security;
alter table public.posts enable row level security;
alter table public.media enable row level security;

create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1 from public.profiles
    where id = auth.uid() and is_admin = true
  );
$$;

drop policy if exists "profiles_self_read" on public.profiles;
create policy "profiles_self_read" on public.profiles
for select to authenticated
using (id = auth.uid());

drop policy if exists "teams_public_read" on public.teams;
create policy "teams_public_read" on public.teams
for select to anon, authenticated
using (true);

drop policy if exists "teams_admin_write" on public.teams;
create policy "teams_admin_write" on public.teams
for all to authenticated
using (public.is_admin())
with check (public.is_admin());

drop policy if exists "posts_public_read" on public.posts;
create policy "posts_public_read" on public.posts
for select to anon, authenticated
using (true);

drop policy if exists "posts_admin_write" on public.posts;
create policy "posts_admin_write" on public.posts
for all to authenticated
using (public.is_admin())
with check (public.is_admin());

drop policy if exists "media_public_read" on public.media;
create policy "media_public_read" on public.media
for select to anon, authenticated
using (true);

drop policy if exists "media_admin_write" on public.media;
create policy "media_admin_write" on public.media
for all to authenticated
using (public.is_admin())
with check (public.is_admin());

-- Storage bucket
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'media',
  'media',
  true,
  15728640,
  array['image/jpeg','image/png','image/webp','video/mp4','video/webm']
)
on conflict (id) do update
set public=true,
    file_size_limit=15728640,
    allowed_mime_types=array['image/jpeg','image/png','image/webp','video/mp4','video/webm'];

drop policy if exists "media_bucket_public_read" on storage.objects;
create policy "media_bucket_public_read" on storage.objects
for select to anon, authenticated
using (bucket_id='media');

drop policy if exists "media_bucket_admin_insert" on storage.objects;
create policy "media_bucket_admin_insert" on storage.objects
for insert to authenticated
with check (bucket_id='media' and public.is_admin());

drop policy if exists "media_bucket_admin_delete" on storage.objects;
create policy "media_bucket_admin_delete" on storage.objects
for delete to authenticated
using (bucket_id='media' and public.is_admin());

-- Después de crear tu usuario en Authentication > Users,
-- reemplaza TU_USER_UUID y ejecuta:
-- insert into public.profiles (id,is_admin)
-- values ('TU_USER_UUID', true)
-- on conflict (id) do update set is_admin=true;
